name: Build and Publish docker images (python 3.8)

on:
  push:
    branches:
      - main
    paths:
      - "3.8/**"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract python version
        run: echo "PYTHON_VERSION=$(grep FROM 3.8/Dockerfile | awk -F'[:-]' '{ print $2 }')" >> $GITHUB_ENV

      - name: Extract poetry version
        run: echo "POETRY_VERSION=$(grep POETRY_VERSION= 3.8/Dockerfile | awk -F'=' '{ print $2 }')" >> $GITHUB_ENV

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: "3.8"
          tags: |
            ghcr.io/shini4i/python-poetry:3.8-${{ env.POETRY_VERSION }}
            ghcr.io/shini4i/python-poetry:${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
          push: true
