name: Update Readme

on:
  workflow_run:
    workflows:
     - "Build and Publish docker images (python 3.8)"
     - "Build and Publish docker images (python 3.9)"
     - "Build and Publish docker images (python 3.10)"
    branches: [main]
    types:
      - completed

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt
      - run: python update-readme.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(readme): update images table [skip ci]"
          file_pattern: "README.md"
