name: Update Readme

on:
  workflow_run:
    workflows:
      - "Build and Publish docker images (python 3.8)"
      - "Build and Publish docker images (python 3.9)"
      - "Build and Publish docker images (python 3.10)"
      - "Build and Publish docker images (python 3.11)"
    branches: [main]
    types:
      - completed

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'

  update-readme:
    needs: pre_job
    name: Update Readme
    runs-on: ubuntu-latest
    if: needs.pre_job.outputs.should_skip != 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt
      - run: python update-readme.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          commit_message: "docs(readme): update images table [skip ci]"
          file_pattern: "README.md"
